# Minimal Wayland client build (note: Wayland client is unmaintained upstream)
set(WITH_CLIENT ON CACHE BOOL "preset")
set(WITH_WAYLAND ON CACHE BOOL "preset")
set(WITH_X11 OFF CACHE BOOL "preset")
set(WITH_CLIENT_SDL OFF CACHE BOOL "preset")
set(WITH_SERVER OFF CACHE BOOL "preset")
set(WITH_SAMPLE OFF CACHE BOOL "preset")
set(WITH_FFMPEG ON CACHE BOOL "preset")
set(WITH_SWSCALE ON CACHE BOOL "preset")
